# Lab 7: Dynamic Programming

Lab associated with Module 7: Dynamic Programming

***

In [1]:
# The following lines are used to increase the width of cells to utilize more space on the screen 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

C:\Users\jarac\AppData\Local\Temp\ipykernel_10768\1945220536.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


***

### Section 0: Imports

In [2]:
import numpy as np

In [3]:
import math

In [4]:
from IPython.display import Image
from graphviz import Digraph

Details of Digraph package: https://h1ros.github.io/posts/introduction-to-graphviz-in-jupyter-notebook/

***

### <font color='red'> Section 1: Write the code for finding the Longest Common Sub-sequence. Make sure you output the Matrix C and the longest sub-sequence. Test your code with various use-cases. </font>

In [92]:
### TODO ###
### Good Luck ###

#NEED TO PRINT LONGEST SUBSEQUENCE 

def lowestCS(x, y):
    #Finds the lengths of the x and y sequences
    a = len(x)
    b = len(y)

    #Creates the matrix and populates it as all zeros
    matrix = np.zeros((a+1, b+1))
    
    for i in range(a+1):
        for j in range (b+1):
            if i == 0 or j ==0:
                matrix[i][j] = 0
            #case 1 
            elif x[i-1] == y[j-1]:
                matrix[i][j] = matrix[i-1][j-1]+1
            #case 2
            else:
                matrix[i][j] = max(matrix[i-1][j], matrix[i][j-1])
    
    #String variable for the LCS 
    lcs = ""
    i = a
    j = b
    
    while i >0 and j>0:
        #if the character being explored in x[] and y are the same, then it belongs in the LCS
        if x[i-1] == y[j-1]:
            lcs += x[i-1]
            i -= 1
            j -= 1
        
        #if the character being explored is not the same then find the max of the 2 and go in the larger number direction
        elif matrix[i-1][j] > matrix[i][j-1]:
            i -= 1
        else: j -= 1
    #The matrix is traversed bottom up 
    #LCS will be the reverse
    lcs = lcs[:: -1]
    #Write up of both sequences and the lcs 
    print ("LCS of " + x + " and " + y + " is " + lcs)
                      
    #Prints the matrix            
    print(matrix)
    #returns the Longest common sub sequence length 
    return matrix[a][b]

    


# Lowest Common Subsequence Tests

In [93]:
x = "ACGGA"
y = "ACTG"

In [94]:
lowestCS(x,y)

LCS of ACGGA and ACTG is ACG
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2.]
 [0. 1. 2. 2. 3.]
 [0. 1. 2. 2. 3.]
 [0. 1. 2. 2. 3.]]


3.0

In [97]:
x2= "BACGFDE"
y2= "BACFD"

In [98]:
lowestCS(x2,y2)

LCS of BACGFDE and BACFD is BACFD
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 3. 3. 3.]
 [0. 1. 2. 3. 3. 3.]
 [0. 1. 2. 3. 4. 4.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


5.0

In [99]:
x3 = "CAMI"
y3 = "ANABELLE"

In [100]:
lowestCS(x3, y3)

LCS of CAMI and ANABELLE is A
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1.]]


1.0

In [101]:
x4 = "SUPERCALIFRAGALISTIC"
y4 = "SUPER"

In [102]:
lowestCS(x4, y4)

LCS of SUPERCALIFRAGALISTIC and SUPER is SUPER
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 3. 3. 3.]
 [0. 1. 2. 3. 4. 4.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


5.0

In [103]:
#2 Subsequences with no overlap
x5 = "ABCDEFGH"
y5 = "IJKLMNO"

In [104]:
lowestCS(x5, y5)

LCS of ABCDEFGH and IJKLMNO is 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


0.0

In [271]:
#2 Subsequences with all overlap
x6 = "CAMILA"
y6 = "CAMILAJ"

In [272]:
lowestCS(x6, y6)

LCS of CAMILA and CAMILAJ is CAMILA
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 3. 3. 3. 3. 3.]
 [0. 1. 2. 3. 4. 4. 4. 4.]
 [0. 1. 2. 3. 4. 5. 5. 5.]
 [0. 1. 2. 3. 4. 5. 6. 6.]]


6.0

***

***

### Section 2: Unbounded Knapsack Problem

Let us build a solution to unbounded Knapsack problem.

In [247]:
#Unlimited item picks within the max weight allowed 
def unboundedKnapsack(W, n, wt, vals, names):
 
    K = [0 for i in range(W + 1)]
    ITEMS = [[] for i in range(W + 1)]
 
    for x in range(1, W + 1):
        K[x] = 0
        for i in range(1, n):
            
            prev_k = K[x]
            
            if (wt[i] <= x):
                K[x] = max(K[x], K[x - wt[i]] + vals[i])
                
            if K[x] != prev_k:
                ITEMS[x] = ITEMS[x - wt[i]] + names[i]
    print("The maximum value aquired is")
    print(K[W])           
    return K[W], ITEMS[W]

In [248]:
W = 4
wt = [1, 2, 3]
vals = [1, 4, 6]
names = [["Turtle"], ["Globe"], ["WaterMelon"]]

n = len(vals)

print('We have {} items'.format(n))                

We have 3 items


In [244]:
K, ITEMS = unboundedKnapsack(W, n, wt, vals, names)

The maximum value aquired is
8


In [245]:
ITEMS

'Globe'

# Unbounded Knapsack Test Cases

In [234]:
W2 = 25
wt2 = [1, 2, 3, 8, 12, 14]
vals2 = [1, 4, 6, 7, 9, 15]
names2 = [["Apple"], ["Pear"], ["Banana"], ["Kiwi"], ["Strawberry"], ["Dragonfruit"]]

n2 = len(vals2)

print('We have {} items'.format(n2))   

We have 6 items


In [235]:
K, ITEMS = unboundedKnapsack(W2, n2, wt2, vals2, names2)

The maximum value aquired is
50


In [149]:
ITEMS

['Banana',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear',
 'Pear']

In [236]:
W3 = 250
wt3 = [3, 6, 9, 12, 15, 18]
vals3 = [1, 4, 6, 7, 9, 15]
names3 = [["Tiger"], ["Penguin"], ["Bear"], ["Kangaroo"], ["Snake"], ["Dragon"]]

n3 = len(vals3)

print('We have {} items'.format(n3))   

We have 6 items


In [237]:
K, ITEMS = unboundedKnapsack(W3, n3, wt3, vals3, names3)

The maximum value aquired is
205


In [238]:
ITEMS

['Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Dragon',
 'Bear',
 'Penguin']

In [252]:
W4 = 70
wt4 = [2, 4, 6, 18, 10, 12]
vals4 = [-3, 16, 9, -2, 8, 18]
names4 = [["Eggs"], ["Chocolate"], ["PeanutButter"], ["Carrots"], ["Steak"], ["Milk"]]

n4 = len(vals4)

print('We have {} items'.format(n4))  

We have 6 items


In [253]:
K, ITEMS = unboundedKnapsack(W4, n4, wt4, vals4, names4)

The maximum value aquired is
272


In [254]:
ITEMS

['Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate',
 'Chocolate']

In [258]:
W5 = 30
wt5 = [2, 4, 6, 8, 10, 12]
vals5 = [-3, -16, 9, -2, -8, -18]
names5 = [["Car"], ["Plane"], ["Train"], ["Boat"], ["Scooter"], ["Skateboard"]]

n5 = len(vals5)

print('We have {} items'.format(n5))  

We have 6 items


In [259]:
K, ITEMS = unboundedKnapsack(W5, n5, wt5, vals5, names5)

The maximum value aquired is
45


In [260]:
ITEMS

['Train', 'Train', 'Train', 'Train', 'Train']

In [ ]:
# ------------------------------
# Code Reflections
# ------------------------------
'''
The idea is to optimally fill a bag of a given capacity with objects that have individual size (weight) and benefit (value)
The unbounded knapsack allows repetition of items until reaching the maximum weight threshold. 
The provided method takes in the W capacity, n number of items, wt weight of those given items, vals the individual value of each item, and the names of the items.
As is evident in the test cases above repetition of items occurs if it is in the best interest of reaching the maximum value.
I added an extra print to establish the maximum value acquired by the implementation.
I also added test cases with negative values.

'''


***

### <font color='red'> Section 3: In the earlier activity, you analysed the code for unbounded knapsack. Based on the algorithm discussed in this section, implement an solution to do 0/1 Knapsack. Make sure you test your algorithms for various test-cases. </font>

In [266]:
#### TODO ####
### Good Luck ###

def zeroOneKnap(W, n, wt, vals):
    K = [[0 for x in range(W + 1)] for x in range(n + 1)]
    # Build table K[][] in bottom up manner
    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                K[i][w] = 0
            elif wt[i-1] <= w:
                #case 2
                K[i][w] = max(vals[i-1]+ K[i-1][w-wt[i-1]], K[i-1][w])
            else:
                K[i][w] = K[i-1][w]
                
    print("The maximum possible value for the knapsack acquired is ")
    return K[n][W]


# 0/1 Knapsack Test Cases

Class Room Test-case

In [267]:
W = 10
V = [20, 8, 14, 13, 35]
wt = [6, 2, 4, 3, 11]

n = len(V)

print('We have {} items'.format(n))   

We have 5 items


In [268]:
zeroOneKnap(W, n, wt, V)

The maximum possible value for the knapsack acquired is 


35

In [264]:
W2 = 50
wt2 = [10, 20, 30]
vals2 = [60, 100, 120]

n2 = len(vals2)

print('We have {} items'.format(n2))   

We have 3 items


In [265]:
zeroOneKnap(W2, n2, wt2, vals2)

The maximum possible value acquired is 


220

In [211]:
W3 = 20
wt3 = [5, 10, 15]
vals3 = [5, 20, 15]

n3 = len(vals3)
print('We have {} items'.format(n3))   

We have 3 items


In [212]:
zeroOneKnap(W3, n3, wt3, vals3)

The maximum possible value acquired is 


25

In [207]:
W4 = 70
wt4 = [2, 4, 6, 18, 10, 12]
vals4 = [-3, 16, 9, -2, 8, 18]

n4 = len(vals4)
print('We have {} items'.format(n4))   

We have 6 items


In [208]:
zeroOneKnap(W4, n4, wt4, vals4)

The maximum possible value acquired is 


51

In [275]:
W5 = 20
wt5 = [2, 4, 6, 8, 10, 12]
vals5 = [5, 10, 1, 15, 20, 25]

n5 = len(vals5)
print('We have {} items'.format(n5))   

We have 6 items


In [274]:
zeroOneKnap(W5, n5, wt5, vals5)

The maximum possible value for the knapsack acquired is 


76

In [276]:
W6 = 10
wt6 = [1, 2, 3, 8, 7, 4]
vals6 = [20, 5, 10, 40, 15, 25]

n6 = len(vals6)
print('We have {} items'.format(n6))  

We have 6 items


In [277]:
zeroOneKnap(W6, n6, wt6, vals6)

The maximum possible value for the knapsack acquired is 


60

***

***